POST http://localhost:7070/api/auth/register

{
"username": "Alll",
"password": "1234",
"email": "apll@hhhh.com",
"phoneNumber": 99324422

}

###
POST http://localhost:7070/api/auth/login

{
 "username": "Alll",
 "password": "1234"
}

###

POST http://localhost:7070/api/user/list/create
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJuYW1lIjoiQXB1ZGQiLCJzdWIiOiJBcHVkZCIsImV4cCI6MTcxNjgxNzE4Niwicm9sZXMiOiJ1c2VyIn0.bITk-j30zL1mHJkGggx5u24g-lJEfG3DjhCbHnh9-xI
Content-Type: application/json

{
  "title": "apples",
  "date": "2024-05-01",
  "capacity": 25,
  "price": 2.33,
  "status": "Not done"
}

###

GET http://localhost:7070/api/user/list
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJuYW1lIjoiQXB1ZGQiLCJzdWIiOiJBcHVkZCIsImV4cCI6MTcxNjgxNzE4Niwicm9sZXMiOiJ1c2VyIn0.bITk-j30zL1mHJkGggx5u24g-lJEfG3DjhCbHnh9-xI